### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by Peepijeep** [magnuschase293/comic_getter#1]
That script is amazing.

But can you please build a windows binary so I don't need pyhton?

**Comment by magnuschase293** [comment]
I have no idea how to do it, but I'll look into it.

**Comment by magnuschase293** [comment]
After doing some research I found a way, but I consider it is best to do it only for the python interpreter and the other python dependencies because the chromedriver depends on the version of chrome users have installed and is senseless to force them to reinstall chrome. Besides I have detailed explanations on how to get the installer from the internet.

**Comment by magnuschase293** [comment]
I have spent a couple of hours attempting to create the binary and I couldn't do it. If any one has any idea on how to do it, feel free to try.

**Comment by magnuschase293** [comment]
Finally manage do the executable.
