### ISSUE TITLE
Converting to .cbz

### ISSUE THREAD

**Issue by vengeance101** [magnuschase293/comic_getter#5]
I think it would be great to add a -cbz tag, which would save the comics as a .cbz instead of individual images.

A .cbz is just a zipped set of images with the extension renamed. Should be very easy!

**Comment by magnuschase293** [comment]
I'll look into it maybe I can also add a -pdf tag.

**Comment by StrangeDOS** [comment]
I agree.  Adding an option for converting to .cbz/.cbr would be great!  Also, you could add an option to keep or delete the .jpg files after the .cbz/.cbr is created.  That would be awesome!

**Comment by StrangeDOS** [comment]
Oh...and if you did this, it would be even better if you named the .cbz/cbr files using the title name.  

Example:  If you downloaded using URL https://readcomiconline.to/Comic/Hack-Slash-My-First-Maniac

You'd end up with a directory named Hack-Slash-My-First-Maniac with .cbz/.cbr files listed...
Hack-Slash-My-First-Maniac Issue-1.cbz
Hack-Slash-My-First-Maniac Issue-2.cbz
Hack-Slash-My-First-Maniac Issue-3.cbz
Hack-Slash-My-First-Maniac Issue-4.cbz

**Comment by magnuschase293** [comment]
There is an inconvenient with throwing all .cbz issues within a collection without making the corresponding directories. The problem lies in the fact the script depends on the directory structure to check if an issue has or hasn't been downloaded. Besides it is kind of a simple way for users to resume a download by deleting the last incomplete issue folder.

A possible solution is to include each .cbz in it's containing directory or to leave the empty directories. I don't know which do you think is better.

**Comment by StrangeDOS** [comment]
Actually that's what I was suggesting.  I probably just didn't explain myself well.  Having the .cbz files for each title inside the corresponding directories makes sorting so much easier.  :)

**Comment by magnuschase293** [comment]
Perfect I will work on it. I might implement a -k flag to keep the jpgs didn't thought someone might want both until you mentioned it.

**Comment by StrangeDOS** [comment]
It makes it easier for stuff later.  I like to remove the obnoxious extra pages that the scanners put in the book.  Its easier to spot them if I still have the jpgs. 👍

**Comment by magnuschase293** [comment]
It is done.
