### ISSUE TITLE
Add range select for volumes.

### ISSUE THREAD

**Issue by vengeance101** [magnuschase293/comic_getter#8]
Some volumes have hundreds of issues, and it's not always reasonable to say "skip the first 400, but download everything else". A range option might be very useful here:

`python3 path/to/__main__.py -i https://readcomiconline.to/Comic/Uncanny-X-Men-1963 -r 94-279`

However, there is the issue that issue 94 is usually _not_ the 94th link on the page (due to annuals, negative numbered issues, and other things). This was a huge problem I had with Xonshiz's tool. I'm not sure I see an immediate solution to it. The range will still work, but if we could somehow make the user able to target issues with a bit more precision it would be very valuable.

**Comment by magnuschase293** [comment]
The numeric indexing problem that you mentioned also in [issue 7](https://github.com/magnuschase293/comic_getter/issues/7) is hard to solve. I have known of this since I added the feature, but it was an easy solution. 

A possibility is to ask the user for a partial name of the issue (of the first and last issue if we are talking about a range). And find he first appearance of such pattern in a list of names ordered as the user sees them.

This solution will depend entirely on the user being able to identify a unique id for the issue.

On the other hand the idea of implementing a range will entirely depend on the targeting system used (name or index). The index system can be easily applicable after all -s flag works by modifying a slice's start value. Maybe I replace -s flag for -r and default it to include first and last issues if not specified.

**Comment by magnuschase293** [comment]
The numeric indexing problem that you mentioned also in issue 7 is hard to solve. I have known of this since I added the feature, but it was an easy solution.

A possibility is to ask the user for a partial name of the issue (of the first and last issue if we are talking about a range). And find he first appearance of such pattern in a list of names ordered as the user sees them.

This solution will depend entirely on the user being able to identify a unique id for the issue.

On the other hand the idea of implementing a range will entirely depend on the targeting system used (name or index). The index system can be easily applicable after all -s flag works by modifying a slice's start value. Maybe I replace -s flag for -r and default it to include first and last issues if not specified.

**Comment by magnuschase293** [comment]
Solved on v1.7.1-alpha
